# A brief introduction of Numpy 

Some online resources:

http://wiki.scipy.org/Tentative_NumPy_Tutorial 

http://wiki.scipy.org/NumPy_for_Matlab_Users

http://www.engr.ucsb.edu/~shell/che210d/numpy.pdf

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities


In [5]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


## 1) Get started

The `numpy` package (module) is used in almost all numerical computation using Python. It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), performance is very good. 

To use `numpy` functions and routines, you need to import `numpy`. As we already learnded, there are several ways to import a module.  For example, you can:


In [75]:
import numpy as np
np.random.rand() # print a random number from uniform distribution

0.3633607463584807

Sometimes you just want to load a specific function, then you can use `from numpy.xxx import yy` command

In [76]:
from numpy.random import rand
print rand(10) #generate an array with 10 random numbers from uniform distribution
help(rand) # you can also get help on this function

[ 0.60951955  0.62996003  0.80558112  0.51317699  0.81478861  0.34444007
  0.38021842  0.97945506  0.64402595  0.98739832]
Help on built-in function rand:

rand(...)
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should all be positive.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Notes
    -----
    This is a convenience function. If you want an interface that
    takes a shape-tuple as the first argument, refer to
    np.random.random_sample .
    
    Examples
    --------
    >>> np.random.rand(3,2)
    array([[ 0.14022471,  0.96360618],  #random
 

`Numpy` has a large library of internal functions and routines

For a complete list check this link: http://docs.scipy.org/doc/numpy/reference/routines.html

## 2) `Numpy` arrays

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

## 2.1) create `Numpy` array

### From lists

For example, to create new vector and matrix arrays from Python lists we can use the `numpy.array` function.

In [79]:
# a vector: the argument to the array function is a Python list
a=[1,2,3,4, 2,1]
v = np.array(a)
print a, v
print type(a)
print type(v) # a is a Python list, v is a numpy list
v.

[1, 2, 3, 4, 2, 1] [1 2 3 4 2 1]
<type 'list'>
<type 'numpy.ndarray'>
2 2


In [80]:
# a matrix: the argument to the array function is a nested Python list
M = array([[1, 2], [3, 4]]) # the first row is [1,2] the second row is [3,4]

print M
print M.dtype

[[1 2]
 [3 4]]
int64


The `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides.

In [28]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

The difference between the `v` and `M` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [29]:
print v
v.shape

[1 2 3 4 2 1]


(6,)

In [30]:
M.shape

(2, 2)

The number of elements in the array is available through the `ndarray.size` property:

In [31]:
print 'v.size',v.size
print 'M.size',M.size

v.size 6
M.size 4


Equivalently, we could use the function `numpy.shape` and `numpy.size`

In [32]:
shape(M)

(2, 2)

In [33]:
size(M)

4

So far the `numpy.ndarray` looks awefully much like a Python list (or nested list). Why not simply use Python lists for computations instead of creating a new array type? 

There are several reasons:

* Python lists are very general. They can contain any kind of object. They are dynamically typed. They do not support mathematical functions such as matrix and dot multiplications, etc. Implementating such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are **statically typed** and **homogeneous**. The type of the elements is determined when array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of `numpy` arrays can be implemented in a compiled language (C and Fortran is used).

Using the `dtype` (data type) property of an `ndarray`, we can see what type the data of an array has:

In [74]:
M.dtype

dtype('int64')

Be very careful when you try to assign a value of the different type to an element in a numpy array:

In [81]:
M = np.array([[1, 2], [3, 4]])
#M=M.astype(float)
print M.dtype
print 'before',M
M[0,0]=100000.5
print 'after',M

int64
before [[1 2]
 [3 4]]
after [[100000      2]
 [     3      4]]


If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [82]:
M = array([[1, 2], [3, 4]], dtype=float)

M[0,0]=1.8
print M # M[0,0] would not change because it is an integer type

[[ 1.8  2. ]
 [ 3.   4. ]]


Common type that can be used with `dtype` are: `int`, `float`, `complex`, `bool`, `object`, etc.

We can also explicitly define the bit size of the data types, for example: `int64`, `int16`, `float128`, `complex128`.

### Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generates arrays of different forms. Some of the more common are:

#### arange

In [83]:
# create a range
#help(arange)
x = arange(0, 10, 2) # arguments: start, stop, step
y = arange(10,0,-1)
print x,y
type(x)

[0 2 4 6 8] [10  9  8  7  6  5  4  3  2  1]


numpy.ndarray

In [84]:
x = arange(-1, 1, 0.1)

x

array([ -1.00000000e+00,  -9.00000000e-01,  -8.00000000e-01,
        -7.00000000e-01,  -6.00000000e-01,  -5.00000000e-01,
        -4.00000000e-01,  -3.00000000e-01,  -2.00000000e-01,
        -1.00000000e-01,  -2.22044605e-16,   1.00000000e-01,
         2.00000000e-01,   3.00000000e-01,   4.00000000e-01,
         5.00000000e-01,   6.00000000e-01,   7.00000000e-01,
         8.00000000e-01,   9.00000000e-01])

#### linspace and logspace

In [81]:
# using linspace, both end points ARE included
l=linspace(0, 10, 25)
print l
print l.shape

[  0.           0.41666667   0.83333333   1.25         1.66666667
   2.08333333   2.5          2.91666667   3.33333333   3.75         4.16666667
   4.58333333   5.           5.41666667   5.83333333   6.25         6.66666667
   7.08333333   7.5          7.91666667   8.33333333   8.75         9.16666667
   9.58333333  10.        ]
(25,)


In [132]:
base_10=logspace(0, 10, 10)
base_e=logspace(0, 10, 10, base=e)
print base_10
print  base_e

[  1.00000000e+00   1.29154967e+01   1.66810054e+02   2.15443469e+03
   2.78255940e+04   3.59381366e+05   4.64158883e+06   5.99484250e+07
   7.74263683e+08   1.00000000e+10]
[  1.00000000e+00   3.03773178e+00   9.22781435e+00   2.80316249e+01
   8.51525577e+01   2.58670631e+02   7.85771994e+02   2.38696456e+03
   7.25095809e+03   2.20264658e+04]


#### mgrid

In [133]:
x, y = mgrid[0:5, 0:5] # similar to meshgrid in MATLAB

In [136]:
print x
print y

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [88]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### random data

In [91]:
from numpy import random

In [92]:
# uniform random numbers in [0,1]
random.rand(5,5)

array([[ 0.14223876,  0.58110358,  0.29806331,  0.25879977,  0.70814573],
       [ 0.03017493,  0.44216547,  0.9451327 ,  0.48490192,  0.73055877],
       [ 0.16020053,  0.0524947 ,  0.71252174,  0.05432754,  0.55241887],
       [ 0.91291393,  0.84745556,  0.37297738,  0.72034986,  0.62557763],
       [ 0.10467717,  0.74256999,  0.45838243,  0.2671627 ,  0.79320635]])

In [3]:
# standard normal distributed random numbers
random.randn(5,5)

array([[ 0.23533745,  0.72199736,  0.25686198,  0.85221055, -0.16236415],
       [ 0.42522125, -0.75479789,  0.46070481, -0.18491341, -0.90298076],
       [ 0.40540499, -0.35944446, -1.37274973, -0.55314064,  0.78468405],
       [ 0.37159814,  1.11141565, -0.01531394,  0.09354043,  0.38857845],
       [-1.21845332,  0.22311231,  0.35964751, -0.5112427 , -1.35538805]])

#### diag

In [38]:
# a diagonal matrix
diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [38]:
# diagonal with offset from the main diagonal
diag([1,2,3], k=-1) 

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

#### zeros and ones

In [93]:
zeros((3,3))
x = 

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [95]:
ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### Some Basic functions of  Numpy Array
#### Min and Max

In [137]:
a=np.arange(15).reshape(3,5)
print a
a.max(),a.min()

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


(14, 0)

In [101]:
print(a.shape)
x=a.max(axis=0)
print(x.shape)
y=a.min(axis=1)
print(y.shape)

(3, 5)
(5,)
(3,)


#### Mean and Sum

In [102]:
a.mean(), a.sum()

(7.0, 105)

In [17]:
a.mean(axis=0),a.sum(axis=1)

(array([ 10.,  11.,  12.,  13.,  14.]), array([ 10,  35,  60,  85, 110]))

#### sort and search

In [19]:
x=np.random.random(10)
print x

[ 0.94184856  0.21502982  0.26182528  0.47995149  0.11423478  0.91290402
  0.26181432  0.30893691  0.70568763  0.01852735]


In [21]:
x.sort() # perform in place sort ~ the original array is replaced by the sorted array
print 

[ 0.01852735  0.11423478  0.21502982  0.26181432  0.26182528  0.30893691
  0.47995149  0.70568763  0.91290402  0.94184856]


In [23]:
print x
x.searchsorted(0.5)

[ 0.01852735  0.11423478  0.21502982  0.26181432  0.26182528  0.30893691
  0.47995149  0.70568763  0.91290402  0.94184856]


7

## 2.2) Manipulating arrays

### Numpy Array Indexing

 `Numpy` array indexing is even more flexible and powerful than indexing of normal Python array   

In [103]:
# v is a vector, and has only one dimension, taking one index
v=random.rand(6)
print 'v=',v
print '1:',v[0]
print '2:',v[::2]
print '3:',v[[0,2]] # the array can be indexed by another array (the 1st and 3rd items in the list)

v= [ 0.10028915  0.7060578   0.05985577  0.28390476  0.13488085  0.5429895 ]
1: 0.10028915008
2: [ 0.10028915  0.05985577  0.13488085]
3: [ 0.10028915  0.05985577]


In [107]:
# M is a matrix, or a 2 dimensional array, taking two indices 
M=np.arange(30).reshape(5,6)
print 'M=',M

# basic indexing is M[row,col]
print '1st row of M is', M[0,:]
#print '2nd row and 3rd col of M is', M[1,2]
print M[-2:,:]

M= [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
1st row of M is [0 1 2 3 4 5]
[[18 19 20 21 22 23]
 [24 25 26 27 28 29]]


If we omit an index of a multidimensional array it returns the **whole row** (or, in general, a N-1 dimensional array) 

In [44]:
print 'the first row of M:',M[0,:]

the first row of M: [0 1 2 3 4 5]


The same thing can be achieved with using `:` instead of an index: 

In [62]:
print 'the first row of M:', M[0,:] # row 1 Colon ":" here means "all"

the first row of M: [0 1 2 3 4 5]


In [111]:
print 'the 2nd column of M:', M[:,1] # column 2

the 2nd column of M: [ 1  7 13 19 25]


In [112]:
print 'the 1st and 3rd columns of M:'
print M[:,[0,2]] # column 2

the 1st and 3rd columns of M:
[[ 0  2]
 [ 6  8]
 [12 14]
 [18 20]
 [24 26]]


We can assign new values to elements in an array using indexing:

In [113]:
M[0,0] = 10

In [114]:
M

array([[10,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [115]:
# also works for rows and columns
M[1,:] = 0
print M
M[:,2] = -1
print M

[[10  1  2  3  4  5]
 [ 0  0  0  0  0  0]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[10  1 -1  3  4  5]
 [ 0  0 -1  0  0  0]
 [12 13 -1 15 16 17]
 [18 19 -1 21 22 23]
 [24 25 -1 27 28 29]]


In [116]:
M

array([[10,  1, -1,  3,  4,  5],
       [ 0,  0, -1,  0,  0,  0],
       [12, 13, -1, 15, 16, 17],
       [18, 19, -1, 21, 22, 23],
       [24, 25, -1, 27, 28, 29]])

### Index slicing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array:

In [117]:
A = array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [118]:
A[1:3]

array([2, 3])

Array slices are *mutable*: if they are assigned a new value the original array from which the slice was extracted is modified:

In [119]:
A[1:3] =[ -2,-3]

A

array([ 1, -2, -3,  4,  5])

We can omit any of the three parameters in `M[lower:upper:step]`:

In [7]:
A[::] # lower, upper, step all take the default values

array([ 1, -2, -3,  4,  5])

In [8]:
A[::2] # step is 2, lower and upper defaults to the beginning and end of the array

array([ 1, -3,  5])

In [9]:
A[:3] # first three elements

array([ 1, -2, -3])

In [10]:
A[3:] # elements from index 3

array([4, 5])

Negative indices counts from the end of the array (positive index from the begining):

In [11]:
A = array([1,2,3,4,5])

In [12]:
A[-1] # the last element in the array

5

In [13]:
A[-3:] # the last three elements

array([3, 4, 5])

Index slicing works exactly the same way for multidimensional arrays:

In [120]:
A = array(arange(0,25)).reshape(5,5)

print A

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [121]:
# a block from the original array
A[1:4, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [56]:
# strides
A[::2, ::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

### Fancy indexing (Advanced topics)

Fancy indexing is the name for when an array or list is used in-place of an index: 

In [122]:
print A
row_indices = [1, 2, 3]
print A[row_indices,:] # in this example, the 2nd, 3rd and 4th rows of A will be printed

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [123]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
print A[row_indices, col_indices] 
# row_indices and col_indices must have the exat same shape and size
# they are combined to provide the row&col indices, e.g. row_indices[0] combined with col_indices[0] and so on so forth

[ 6 12 19]


We can also index masks: If the index mask is an Numpy array of with data type `bool`, then an element is selected (True) or not (False) depending on the value of the index mask at the position each element: 

In [124]:
B = np.array(arange(1,6))
B

array([1, 2, 3, 4, 5])

In [125]:
row_mask = array([True, False, True, False, False])
print B[row_mask]

[1 3]


In [126]:
# same thing
row_mask = array([1,0,1,0,0], dtype=bool)
B[row_mask]

array([1, 3])

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [128]:
x = arange(0, 10, 0.5)
x

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [129]:
mask1 = (5 < x)
#print mask1
#print x[mask1]
# mask2 = ( x<7.5)
# print x[mask2]
mask3 = (5 < x) & ( x<7.5)
print mask3
print x[mask3]
# print mask1
# print mask2
# print mask3

[False False False False False False False False False False False  True
  True  True  True  True  True  True  True  True]
[ 5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5]


In [32]:
print x[mask1]
print x[mask2]
print x[mask3]

[ 5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7. ]
[ 5.5  6.   6.5  7. ]


## Basic functions for extracting data from arrays and creating arrays

### where

The index mask can be converted to position index using the `where` function

In [131]:
x = arange(0, 10, 0.5)
print x
# idx = x>5
# print(idx)
indices = np.where(x>5)
print(x[indices])
y=x[indices]

print(x)
print(y)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5]
[ 5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5]
[ 5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5]


In [73]:
print x[indices] # this indexing is equivalent to the fancy indexing x[mask]
print x[where(x>5)]

[ 5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5]
[ 5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5]


### diag

With the diag function we can also extract the diagonal and subdiagonals of an array:

In [48]:
print A
diag(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([ 0,  6, 12, 18, 24])

In [47]:
diag(A, -2)

array([10, 16, 22])

## 3) Linear algebra

Vectorizing code is the key to writing efficient numerical calculation with Python/Numpy. That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.

### Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [111]:
v1 = arange(0, 5)
v1

array([0, 1, 2, 3, 4])

In [112]:
v1 * 2

array([0, 2, 4, 6, 8])

In [113]:
v1 + 2

array([2, 3, 4, 5, 6])

In [114]:
print 'A=    ',A
print 'A * 2=', A * 2
print 'A + 2=', A + 2

A=     [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
A * 2= [[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]
A + 2= [[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]
 [17 18 19 20 21]
 [22 23 24 25 26]]


### Element-wise array-array operations

When we add, subtract, multiply and divide arrays with each other, the default behaviour is **element-wise** operations:

In [148]:
A * A # element-wise multiplication

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [149]:
v1 * v1

array([ 0,  1,  4,  9, 16])

If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row:

In [150]:
A.shape, v1.shape

((5, 5), (5,))

In [53]:
print 'A',A
print 'v1',v1
print 'A * v1=' # v is multipled with every row of A
print A * v1

A [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
v1 [0 1 2 3 4]
A * v1=
[[ 0  1  4  9 16]
 [ 0  6 14 24 36]
 [ 0 11 24 39 56]
 [ 0 16 34 54 76]
 [ 0 21 44 69 96]]


### Matrix algebra

What about matrix mutiplication? There are two ways. We can either use the `dot` function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments: 

In [116]:
A*A
dot(A, A)

array([[ 150,  160,  170,  180,  190],
       [ 400,  435,  470,  505,  540],
       [ 650,  710,  770,  830,  890],
       [ 900,  985, 1070, 1155, 1240],
       [1150, 1260, 1370, 1480, 1590]])

In [117]:
dot(A, v1)

array([ 30,  80, 130, 180, 230])

In [118]:
dot(v1, v1)

30

Alternatively, we can cast the array objects to the type `matrix`. This changes the behavior of the standard arithmetic operators `+, -, *` to use matrix algebra.

In [119]:
M = matrix(A)
v = matrix(v1).T # make it a column vector

In [120]:
v

matrix([[0],
        [1],
        [2],
        [3],
        [4]])

In [121]:
M * M

matrix([[ 150,  160,  170,  180,  190],
        [ 400,  435,  470,  505,  540],
        [ 650,  710,  770,  830,  890],
        [ 900,  985, 1070, 1155, 1240],
        [1150, 1260, 1370, 1480, 1590]])

In [122]:
M * v

matrix([[ 30],
        [ 80],
        [130],
        [180],
        [230]])

In [118]:
# inner product
v.T * v

matrix([[30]])

In [119]:
# with matrix objects, standard matrix algebra applies
v + M*v

matrix([[ 30],
        [131],
        [232],
        [333],
        [434]])

If we try to add, subtract or multiply objects with incomplatible shapes we get an error:

In [120]:
v = matrix([1,2,3,4,5,6]).T

In [99]:
shape(M), shape(v)

((5, 5), (6, 1))

In [166]:
M * v

matrix([[ 30],
        [ 80],
        [130],
        [180],
        [230]])

See also the related functions: `inner`, `outer`, `cross`, `kron`, `tensordot`. Try for example `help(kron)`.

### Matrix computations

#### Inverse

In [108]:
inv(C) # equivalent to C.I 

matrix([[ 0.+2.j ,  0.-1.j ],
        [ 0.-1.5j,  0.+0.5j]])

In [109]:
C.I * C

matrix([[  1.00000000e+00+0.j,   4.44089210e-16+0.j],
        [  0.00000000e+00+0.j,   1.00000000e+00+0.j]])

#### Determinant

In [110]:
det(C)

(2.0000000000000004+0j)

In [111]:
det(C.I)

(0.50000000000000011+0j)